### ISSUE TITLE
practicas

### ISSUE THREAD

**Issue by grupohernandezalba** [DiegooDV/Georeferencing-Apps#3]
Hola @DiegooDV muy buen trabajo , me gusto la funcionalidad y el diseño. Solo una recomendación creo que usaste un tema, mejor hazlo tu mismo con html.

![Captura de Pantalla 2020-03-01 a la(s) 12 09 56](https://user-images.githubusercontent.com/14998558/75631116-bf9a7380-5bb5-11ea-96d5-f0c6db8ca674.png)

**Comment by DiegooDV** [comment]
Hola @grupohernandezalba ¿Cúal tema? o ¿En qué sección?

**Comment by grupohernandezalba** [comment]
Tienes razón no se uso ningún tema, ya verifique y vi que usaste un css personal con las propiedades de opacity, quedo muy bien, buen trabajo.
