### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by grupohernandezalba** [DiegooDV/Georeferencing-Apps#4]
Muy bien @DiegooDV trata de implementar la opción de editar para que quede mejor.

![Captura de Pantalla 2020-03-12 a la(s) 21 34 12](https://user-images.githubusercontent.com/14998558/76587404-654cbd00-64a9-11ea-8b24-73a7c6390792.png)

**Comment by DiegooDV** [comment]
Listo! @grupohernandezalba

**Comment by grupohernandezalba** [comment]
Muy bien Diego ya quedo mejor solo cuando des click en UPDATE jala el valor de nombre y código a los INPUT, vi que usas sweetAlert, fijate que yo lo llegue usar y en algunos navegadores tuve problemas , checa la compatibilidad con otros navegadores.


![Captura de Pantalla 2020-03-16 a la(s) 16 38 02](https://user-images.githubusercontent.com/14998558/76805588-cecc1480-67a4-11ea-9076-d1c5a016b6e3.png)
