### ISSUE TITLE
Aviso

### ISSUE THREAD

**Issue by grupohernandezalba** [DiegooDV/Georeferencing-Apps#5]
Hola @DiegooDV 

Anexo video de la clase del día de hoy 

Firebase practica2, se optimizo la practica1 agregando la opción de editar productos y usando POO.:

https://youtu.be/r1uSXT_2Qos

Las practicas ya están actualizadas en GitHub:
https://github.com/grupohernandezalba/sistemasgeo

Les recuerdo que los videos los pueden accesar también desde el drive compartido:

http://bit.ly/sistemasgeo

**Comment by DiegooDV** [comment]
Gracias @grupohernandezalba , una pregunta profesor, en caso de ya haber agregado la caracteristica de editar en la practica 1, ¿Es necesario crear la practica 2? ¿O ya con la 1ra nada mas esta bien?

**Comment by grupohernandezalba** [comment]
En tu caso ya adelantaste, solo organiza bien tu practica en archivos como
se menciona en el video.

saludos




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
18/03/20
09:58:37
